name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Solo cuando hay push en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # Carpeta raíz del proyecto
          publish_branch: gh-pages
